---
- name: Ansible Copy Example Local to Remote
  hosts: demoArc
  tasks:
    - name: copying Backend file with playbook
      become: true
      copy:
        src: ./kubernetes-config
        dest: ./
        owner: jay
        group: jay
        mode: 0644
    - name: Start Minikube
      command: minikube start
    - name: Create namespace
      command: kubectl create namespace socialconnect
    - name: Apply secret file
      command: kubectl apply -f kubernetes-secret.yaml
    - name: Apply frontend
      command: kubectl apply -f kubernetes-frontend.yaml
    - name: Apply backend
      command: kubectl apply -f kubernetes-backend.yaml
    - name: Ingress addons
      command: minikube addons enable ingress
    - name: Apply ingress
      command: kubectl apply -f kubernetes-ingress.yaml
