---
- name: Ansible Copy Example Local to Remote
  hosts: demoArc
  tasks:
    - name: copying Backend file with playbook
      become: true
      copy:
        src: ./kubernetes-config
        dest: ./
        owner: jay
        group: jay
        mode: 0644
