---
- name: Ansible Copy Example Local to Remote
  hosts: demoArc
  tasks:
    - name: copying Backend file with playbook
      become: true
      copy:
        src: ./kubernetes-config
        dest: ./
        owner: jay
        group: jay
        mode: 0644
    - name: Start Minikube
      command: minikube start
    - name: Create namespace
      command: kubectl create namespace socialconnect
