---
- name: Ansible Copy Example Local to Remote
  hosts: demoArc
  tasks:
    - name: copying Backend file with playbook
      become: true
      copy:
        src: ./kubernetes-config
        dest: ./
        owner: jay
        group: jay
        mode: 0644
    - name: Delete minikube
      command: minikube delete
    - name: Start Minikube
      command: minikube start
    - name: Create namespace
      command: kubectl create namespace socialconnect
    - name: Apply secret file
      command: kubectl apply -f kubernetes-config/kubernetes-secret.yaml
    - name: Apply frontend
      command: kubectl apply -f kubernetes-config/kubernetes-frontend.yaml
    - name: Apply Persistant volume
      command: kubectl apply -f kubernetes-config/kubernetes-volume.yaml
    - name: Apply Persistant volume claim
      command: kubectl create -f kubernetes-config/kubernetes-volume-claim.yaml
    - name: Apply backend
      command: kubectl apply -f kubernetes-config/kubernetes-backend.yaml
    - name: Apply ingress
      command: kubectl apply -f kubernetes-config/kubernetes-ingress.yaml
    - name: Ingress addons
      command: minikube addons enable ingress
    - name: Update the /etc/hosts file with node name
      tags: etchostsupdate
      become: yes
      become_user: root
      lineinfile:
        path: '/etc/hosts'
        line: '192.168.49.2    socialconnect.com'
        state: present
        backup: yes
