---
- name: Ansible Copy Example Local to Remote
  hosts: demoArc
  tasks:
    - name: copying file with playbook
      become: true
      copy:
        src: /home/jay/Desktop/Social Platform For Hobbyist/kubernetes-config/kubernetes-backend.yaml
        dest: /home/jay/Desktop
        owner: jay
        group: jay
        mode: 0644
