---
- name: Update the /etc/hosts file with node name
  hosts: demoArc
  tags: etchostsupdate
  become: yes
  become_user: root
  lineinfile:
    path: '/etc/hosts'
    line: '192.168.49.2    socialconnect.com'
    state: present
    backup: yes
