apiVersion: v1
kind: Secret
metadata:
  name: socialconnect-backend-secret
  namespace: socialconnect
type: Opaque
data:
  PORT: MzAwMQ==
  MONGODB_URI_PRODUCTION: bW9uZ29kYitzcnY6Ly9qYXlwYXJla2g6cm9jazEyM0FAcHJvZHVjdGlvbi4wNzRieHJhLm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=
  MONGODB_URI_TESTING: bW9uZ29kYitzcnY6Ly9qYXlwYXJla2g6cm9jazEyM0FAY2x1c3RlcjAuYXdhenNwbi5tb25nb2RiLm5ldC9DbHVzdGVyMD9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHk=